/**
 * @file retirement-data-mocks.ts
 * @description Provides mock data for Retirement calculator unit tests.
 */

import { Tables } from '../../src/types';

export const mockFederalTaxData: Tables<'federal_tax_data'>[] = [
  {
    id: 1,
    year: 2026,
    state: 'Federal',
    filing_status: 'Single',
    tax_rate: 0.1,
    income_bracket_low: 0,
    income_bracket_high: '11000',
    standard_deduction: 13850,
    personal_exemption: 0,
    amt_exemption: 90100,
    eitc_value: 8680,
    eitc_parameter: 'Income at Max Credit',
    children: 'No Children',
  },
  {
    id: 2,
    year: 2026,
    state: 'Federal',
    filing_status: 'Single',
    tax_rate: 0.12,
    income_bracket_low: 11001,
    income_bracket_high: '44725',
    standard_deduction: 13850,
    personal_exemption: 0,
    amt_exemption: 90100,
    eitc_value: 8680,
    eitc_parameter: 'Income at Max Credit',
    children: 'No Children',
  },
  {
    id: 3,
    year: 2026,
    state: 'Federal',
    filing_status: 'Single',
    tax_rate: 0.22,
    income_bracket_low: 44726,
    income_bracket_high: '95375',
    standard_deduction: 13850,
    personal_exemption: 0,
    amt_exemption: 90100,
    eitc_value: 8680,
    eitc_parameter: 'Income at Max Credit',
    children: 'No Children',
  },
  {
    id: 4,
    year: 2026,
    state: 'Federal',
    filing_status: 'Married Filing Jointly',
    tax_rate: 0.1,
    income_bracket_low: 0,
    income_bracket_high: '22000',
    standard_deduction: 27700,
    personal_exemption: 0,
    amt_exemption: 140200,
    eitc_value: 8680,
    eitc_parameter: 'Income at Max Credit',
    children: 'No Children',
  },
  {
    id: 5,
    year: 2026,
    state: 'Federal',
    filing_status: 'Married Filing Jointly',
    tax_rate: 0.12,
    income_bracket_low: 22001,
    income_bracket_high: '89450',
    standard_deduction: 27700,
    personal_exemption: 0,
    amt_exemption: 140200,
    eitc_value: 8680,
    eitc_parameter: 'Income at Max Credit',
    children: 'No Children',
  },
];

export const mockStateTaxData: Tables<'state_tax_data'>[] = [
  {
    id: 1,
    year: 2025,
    state: 'CA',
    filing_status: 'Single',
    tax_rate: 0.01,
    income_bracket_low: 0,
    income_bracket_high: '10412',
    standard_deduction: 5202,
    personal_exemption: 0,
    amt_exemption: null,
    "Income at Max Credit_No Children": null,
    "Income at Max Credit_One Child": null,
    "Income at Max Credit_Three or More Children": null,
    "Income at Max Credit_Two Children": null,
    "Maximum Credit_No Children": null,
    "Maximum Credit_One Child": null,
    "Maximum Credit_Three or More Children": null,
    "Maximum Credit_Two Children": null,
    "Phaseout Begins_No Children": null,
    "Phaseout Begins_One Child": null,
    "Phaseout Begins_Three or More Children": null,
    "Phaseout Begins_Two Children": null,
    "Phaseout Ends (Credit Equals Zero)_No Children": null,
    "Phaseout Ends (Credit Equals Zero)_One Child": null,
    "Phaseout Ends (Credit Equals Zero)_Three or More Children": null,
    "Phaseout Ends (Credit Equals Zero)_Two Children": null,
  },
  {
    id: 2,
    year: 2025,
    state: 'CA',
    filing_status: 'Single',
    tax_rate: 0.02,
    income_bracket_low: 10413,
    income_bracket_high: '24684',
    standard_deduction: 5202,
    personal_exemption: 0,
    amt_exemption: null,
    "Income at Max Credit_No Children": null,
    "Income at Max Credit_One Child": null,
    "Income at Max Credit_Three or More Children": null,
    "Income at Max Credit_Two Children": null,
    "Maximum Credit_No Children": null,
    "Maximum Credit_One Child": null,
    "Maximum Credit_Three or More Children": null,
    "Maximum Credit_Two Children": null,
    "Phaseout Begins_No Children": null,
    "Phaseout Begins_One Child": null,
    "Phaseout Begins_Three or More Children": null,
    "Phaseout Begins_Two Children": null,
    "Phaseout Ends (Credit Equals Zero)_No Children": null,
    "Phaseout Ends (Credit Equals Zero)_One Child": null,
    "Phaseout Ends (Credit Equals Zero)_Three or More Children": null,
    "Phaseout Ends (Credit Equals Zero)_Two Children": null,
  },
  {
    id: 3,
    year: 2025,
    state: 'TX', // A state with no income tax
    filing_status: 'Single',
    tax_rate: 0,
    income_bracket_low: 0,
    income_bracket_high: 'inf',
    standard_deduction: 0,
    personal_exemption: 0,
    amt_exemption: null,
    "Income at Max Credit_No Children": null,
    "Income at Max Credit_One Child": null,
    "Income at Max Credit_Three or More Children": null,
    "Income at Max Credit_Two Children": null,
    "Maximum Credit_No Children": null,
    "Maximum Credit_One Child": null,
    "Maximum Credit_Three or More Children": null,
    "Maximum Credit_Two Children": null,
    "Phaseout Begins_No Children": null,
    "Phaseout Begins_One Child": null,
    "Phaseout Begins_Three or More Children": null,
    "Phaseout Begins_Two Children": null,
    "Phaseout Ends (Credit Equals Zero)_No Children": null,
    "Phaseout Ends (Credit Equals Zero)_One Child": null,
    "Phaseout Ends (Credit Equals Zero)_Three or More Children": null,
    "Phaseout Ends (Credit Equals Zero)_Two Children": null,
  },
];
